name: Update arlington branch

on:
  push:
    branches:
      - integration
    paths-ignore:
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-1A.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-1B.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2A.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2B.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-2U.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3A.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3B.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-3U.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4E.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFA-4F.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml'
      - 'core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-2-ISO32005.xml'

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 16, 17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: integration
      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Fetch arlington branch and checkout
        run: |
          git fetch origin arlington:arlington
          git checkout -b test-branch arlington
      - name: Configure user nameF
        run: |
          git config user.name "Git User"
          git config user.email "user@test.com"
      - name: Add commit to the test branch
        run: git cherry-pick -m 1 ${{ github.sha }}
      - name: Build project with Maven
        if: success()
        run: mvn --batch-mode --update-snapshots verify

  merge:
    runs-on: ubuntu-latest
    needs: checkout-and-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: integration
      - name: Generate new branch name
        id: new-branch-name
        run: echo "branch_name=new-branch-$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Fetch arlington branch and checkout
        run: |
          git fetch origin arlington:arlington
          git checkout -b ${{ steps.new-branch-name.outputs.branch_name }} arlington
      - name: Configure user name
        run: |
          git config user.name "Git User"
          git config user.email "user@temp.com"
      - name: Add commit to new branch
        run: git cherry-pick -m 1 ${{ github.sha }}
      - name: Merge branch into arlington
        if: success()
        run: |
          git push origin ${{ steps.new-branch-name.outputs.branch_name }}
          git checkout arlington
          git merge ${{ steps.new-branch-name.outputs.branch_name }}
          git push origin arlington
      - name: Delete new branch
        run: git push origin --delete ${{ steps.new-branch-name.outputs.branch_name }}

  send-notification:
    runs-on: ubuntu-latest
    needs: [checkout-and-build, merge]
    if: |
      always() &&
      (contains(needs.*.result, 'failure') ||
      contains(needs.*.result, 'skipped') ||
      contains(needs.*.result, 'cancelled'))
    steps:
      - name: Send notification if build or merge failed
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03E3JJGLQL
          status: FAILED
          color: danger
